Repository pennlabs/penn-clubs, pull requests merged in 2020-01, with the labels that each got.

#60 Strip Social Urls to Decrease Their Length
  components/ClubPage/SocialIcons.js
  components/ClubPage/SocialLink.js
Labels: enhancement

#62 Convert SearchBar into Functional Component
  components/SearchBar.js
  package.json
  yarn.lock
Labels: enhancement

#64 Logout Button
  components/Header/Links.js
  components/Settings/ProfileTab.js
  static/img/icons/log-out.svg
  utils.js
Labels: enhancement, question

#61 Various improvements
  components/ClubCard.js
  components/ClubList.js
  components/ClubPage/Header.js
  components/ClubTableRow.js
  components/Form.js
  components/Settings/ClubTab.js
  components/Settings/FavoritesTab.js
  components/Settings/ProfileTab.js
  components/TabView.js
  components/common/Icon.js
  components/common/SubscribeIcon.js
  components/common/index.js
  pages/club.js
  pages/edit.js
  pages/invite.js
  pages/settings.js
  renderPage.js
  static/img/icons/bell-off.svg
  static/img/icons/bell.svg
  yarn.lock
Labels: bug, enhancement

#63 Bookmarks Persist After Toggle in Profile
  components/Settings/FavoritesTab.js
  renderPage.js
  yarn.lock
Labels: enhancement

#68 Style homepage background
  components/ClubPage/Actions.js
  components/DisplayButtons.js
  components/SearchBar.js
  pages/index.js
Labels: enhancement

#56 Render Club Page Server Side
  components/TabView.js
  pages/club/[club]/index.js
Labels: enhancement

#65 Implement club fair pages
  README.md
  components/ClubPage/InfoBox.js
  components/ClubPage/Testimonials.js
  components/ClubTableRow.js
  components/Form.js
  components/Settings/ClubTab.js
  components/Settings/ProfileForm.js
  components/Settings/ProfileTab.js
  components/common/Icon.js
  components/common/Typography.js
  constants/colors.js
  pages/club/[club]/edit.js
  pages/club/[club]/fair.js
  pages/club/[club]/flyer.js
  pages/club/[club]/index.js
  pages/index.js
  pages/invite/[club]/[invite]/[token]/index.js
  pages/settings.js
  pages/welcome.js
  public/static/img/icons/chevron-up.svg
  public/static/img/icons/download.svg
  public/static/img/icons/triangle.svg
  renderPage.js
  utils.js
Labels: enhancement

#69 Add Close Icon When Filtering by Tags on Mobile
  frontend/components/DropdownFilter.js
  frontend/components/SearchBar.js
Labels: enhancement

#70 Enable Submit Button Only If Changes Were Made
  frontend/components/Form.js
  frontend/components/Settings/ProfileForm.js
  frontend/pages/club/[club]/edit.js
Labels: enhancement

#66 Add Login Prompt Modal
  .gitignore
  frontend/components/LoginModal.js
  frontend/components/common/Modal.js
  frontend/components/common/Shade.js
  frontend/components/common/index.js
  frontend/constants/animations.js
  frontend/constants/index.js
  frontend/constants/measurements.js
  frontend/package-lock.json
  frontend/package.json
  frontend/renderPage.js
Labels: enhancement

#74 Show Badges on Club Page
  backend/clubs/management/commands/merge_duplicates.py
  backend/clubs/models.py
  backend/clubs/views.py
  backend/pennclubs/settings/base.py
  frontend/components/ClubPage/Header.js
  frontend/components/Form.js
  frontend/components/common/TagGroup.js
  frontend/components/common/Tags.js
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#79 Testimonials
  backend/clubs/mixins.py
  backend/clubs/permissions.py
  backend/clubs/serializers.py
  backend/clubs/urls.py
  backend/clubs/views.py
  backend/tests/clubs/test_views.py
  frontend/components/Form.js
  frontend/pages/club/[club]/edit.js
Labels: enhancement

#83 Fix Bookmark Decrements Bug
  frontend/components/ClubPage/Actions.js
  frontend/renderPage.js
Labels: bug

#87 Add Edit Block Screen for Ppl Without Access
  backend/Pipfile.lock
  frontend/components/common/AuthPrompt.js
  frontend/pages/club/[club]/edit.js
Labels: bug

#80 Club Member Display Redesign
  frontend/components/ClubPage/Actions.js
  frontend/components/ClubPage/Description.js
  frontend/components/ClubPage/MemberCard.js
  frontend/components/ClubPage/MemberList.js
  frontend/components/ClubPage/Tabs.js
  frontend/components/ClubPage/Testimonials.js
  frontend/components/common/Grid.js
  frontend/components/common/ProfilePic.js
  frontend/components/common/index.js
  frontend/constants/colors.js
  frontend/constants/measurements.js
  frontend/pages/club/[club]/flyer.js
  frontend/pages/club/[club]/index.js
  frontend/public/static/img/icons/more-horizontal.svg
  frontend/public/static/img/icons/triangle-testimonial.svg
Labels: enhancement

#91 Fixed
  frontend/components/ClubPage/Actions.js
Labels: bug

#81 Recruitment events
  backend/clubs/migrations/0015_auto_20200119_1422.py
  backend/clubs/models.py
  backend/clubs/permissions.py
  backend/clubs/serializers.py
  backend/clubs/views.py
  backend/tests/clubs/test_views.py
  frontend/components/ClubPage/Events.js
  frontend/components/Form.js
  frontend/pages/club/[club]/edit.js
  frontend/pages/club/[club]/index.js
  frontend/public/static/img/icons/calendar.svg
  frontend/yarn.lock
Labels: enhancement

#96 Add datepicker for event
  frontend/components/Form.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/static/css/react-datepicker.css
Labels: bug

#98 Fix event bugs
  backend/clubs/migrations/0016_auto_20200128_2024.py
  backend/clubs/models.py
  frontend/components/Form.js
Labels: bug

#88 Enforce prettier
  frontend/.eslintrc.json
  frontend/components/ClubCard.js
  frontend/components/ClubDetails.js
  frontend/components/ClubTableRow.js
  frontend/components/DropdownFilter.js
  frontend/components/Form.js
  frontend/components/LoginModal.js
  frontend/components/SearchBar.js
  frontend/components/Settings/ProfileForm.js
  frontend/components/TabView.js
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#100 Embed svgs inline
  frontend/components/DropdownFilter.js
  frontend/components/Footer/index.js
  frontend/components/Form.js
  frontend/components/Header/Feedback.js
  frontend/components/Settings/ClubTabCard.js
  frontend/components/common/Icon.js
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/static/img/icons/box-blue.svg
  frontend/public/static/img/icons/box-red.svg
  frontend/public/static/img/icons/box-yellow.svg
  frontend/public/static/img/icons/check-box-blue.svg
  frontend/public/static/img/icons/check-box-red.svg
  frontend/public/static/img/icons/check-box-yellow.svg
  frontend/public/static/img/icons/check-circle-green.svg
  frontend/public/static/img/icons/edit-white.svg
  frontend/public/static/img/icons/external-link-white.svg
  frontend/public/static/img/icons/heart-red.svg
  frontend/public/static/img/icons/log-out-white.svg
  frontend/public/static/img/icons/message-circle-white.svg
  frontend/public/static/img/icons/x-circle-red.svg
Labels: enhancement

#95 Member card width/padding bug
  frontend/components/common/Grid.js
Labels: bug

#89 Update Color Scheme
  frontend/components/ClubDetails.js
  frontend/components/DropdownFilter.js
  frontend/components/Header/Links.js
  frontend/components/Header/index.js
  frontend/components/Settings/ClubTabCard.js
  frontend/components/common/AuthPrompt.js
  frontend/components/common/Icon.js
  frontend/components/common/Tags.js
  frontend/components/common/Typography.js
  frontend/constants/colors.js
  frontend/pages/club/[club]/flyer.js
  frontend/pages/index.js
  frontend/public/static/favicon.ico
  frontend/public/static/img/newlogo.png
  frontend/public/static/img/pc.png
  frontend/public/static/img/peoplecirclelogo.png
  frontend/public/static/img/peoplelogo.png
  frontend/public/static/img/undercons3.png
  frontend/public/static/img/underconstruction.png
  frontend/public/static/maintenance.html
Labels: enhancement

#99 Add club rank description algorithm
  frontend/components/Form.js
  frontend/components/Settings/ProfileForm.js
  frontend/package.json
  frontend/pages/club/[club]/edit.js
  frontend/pages/faq.js
  frontend/pages/rank.js
Labels: enhancement

#101 SEO for Individual Club Pages
  frontend/components/ClubMetadata.js
  frontend/components/DropdownFilter.js
  frontend/components/Header/Head.js
  frontend/components/common/Icon.js
  frontend/components/common/Metadata.js
  frontend/components/common/Modal.js
  frontend/components/common/index.js
  frontend/pages/_error.js
  frontend/pages/club/[club]/edit.js
  frontend/pages/club/[club]/fair.js
  frontend/pages/club/[club]/flyer.js
  frontend/pages/club/[club]/index.js
  frontend/pages/faq.js
  frontend/pages/index.js
  frontend/pages/invite/[club]/[invite]/[token]/index.js
  frontend/pages/settings.js
  frontend/pages/welcome.js
  frontend/stories/Footer.stories.js
Labels: enhancement
